import { writable } from "svelte/store";
import type { Operator } from "./Types";

// Keymap currently only for display in settings
export const keymap = writable<Operator[]>([
	{
		operator: "play_pause",
		name: "play/pause",
		key: "Spacebar",
		ctrl: false,
		alt: false,
		meta: false,
	},
	{
		operator: "up",
		name: "playlistUp",
		key: "KeyW",
		ctrl: false,
		alt: false,
		meta: false,
	},
	{
		operator: "up",
		name: "PlaylistUp",
		key: "arrowUp",
		ctrl: false,
		alt: false,
		meta: false,
	},
	{
		operator: "down",
		name: "PlaylistDown",
		key: "KeyS",
		ctrl: false,
		alt: false,
		meta: false,
	},
	{
		operator: "down",
		name: "PlaylistDown",
		key: "arrowDown",
		ctrl: false,
		alt: false,
		meta: false,
	},
	{
		operator: "reset",
		name: "resetTrack",
		key: "KeyA",
		ctrl: false,
		alt: false,
		meta: false,
	},
	{
		operator: "reset",
		name: "resetTrack",
		key: "arrowLeft",
		ctrl: false,
		alt: false,
		meta: false,
	},
	{
		operator: "skip",
		name: "skipTrack",
		key: "KeyD",
		ctrl: false,
		alt: false,
		meta: false,
	},
	{
		operator: "skip",
		name: "skipTrack",
		key: "arrowRight",
		ctrl: false,
		alt: false,
		meta: false,
	},
	{
		operator: "hotkey1",
		name: "hotkey1",
		key: "Digit1",
		ctrl: false,
		alt: false,
		meta: false,
	},
	{
		operator: "hotkey2",
		name: "hotkey2",
		key: "Digit2",
		ctrl: false,
		alt: false,
		meta: false,
	},
	{
		operator: "hotkey3",
		name: "hotkey3",
		key: "Digit3",
		ctrl: false,
		alt: false,
		meta: false,
	},
	{
		operator: "hotkey4",
		name: "hotkey4",
		key: "Digit4",
		ctrl: false,
		alt: false,
		meta: false,
	},
	{
		operator: "hotkey5",
		name: "hotkey5",
		key: "Digit5",
		ctrl: false,
		alt: false,
		meta: false,
	},
	{
		operator: "hotkey6",
		name: "hotkey6",
		key: "Digit6",
		ctrl: false,
		alt: false,
		meta: false,
	},
	{
		operator: "hotkey7",
		name: "hotkey7",
		key: "Digit7",
		ctrl: false,
		alt: false,
		meta: false,
	},
	{
		operator: "hotkey8",
		name: "hotkey8",
		key: "Digit8",
		ctrl: false,
		alt: false,
		meta: false,
	},
	{
		operator: "hotkey9",
		name: "hotkey9",
		key: "Digit9",
		ctrl: false,
		alt: false,
		meta: false,
	},
	{
		operator: "hotkey1_clear",
		name: "clearHotkey1",
		key: "Digit1",
		ctrl: false,
		alt: true,
		meta: false,
	},
	{
		operator: "hotkey2_clear",
		name: "clearHotkey2",
		key: "Digit2",
		ctrl: false,
		alt: true,
		meta: false,
	},
	{
		operator: "hotkey3_clear",
		name: "clearHotkey3",
		key: "Digit3",
		ctrl: false,
		alt: true,
		meta: false,
	},
	{
		operator: "hotkey4_clear",
		name: "clearHotkey4",
		key: "Digit4",
		ctrl: false,
		alt: true,
		meta: false,
	},
	{
		operator: "hotkey5_clear",
		name: "clearHotkey5",
		key: "Digit5",
		ctrl: false,
		alt: true,
		meta: false,
	},
	{
		operator: "hotkey6_clear",
		name: "clearHotkey6",
		key: "Digit6",
		ctrl: false,
		alt: true,
		meta: false,
	},
	{
		operator: "hotkey7_clear",
		name: "clearHotkey7",
		key: "Digit7",
		ctrl: false,
		alt: true,
		meta: false,
	},
	{
		operator: "hotkey8_clear",
		name: "clearHotkey8",
		key: "Digit8",
		ctrl: false,
		alt: true,
		meta: false,
	},
	{
		operator: "hotkey9_clear",
		name: "clearHotkey9",
		key: "Digit9",
		ctrl: false,
		alt: true,
		meta: false,
	},
	{
		operator: "projector",
		name: "projector",
		key: "KeyP",
		ctrl: true,
		alt: false,
		meta: false,
	},
	{
		operator: "settings",
		name: "settings",
		key: "Comma",
		ctrl: true,
		alt: false,
		meta: false,
	},
	{
		operator: "save",
		name: "saveProject",
		key: "KeyS",
		ctrl: true,
		alt: false,
		meta: false,
	},
	{
		operator: "open",
		name: "openProject",
		key: "KeyO",
		ctrl: true,
		alt: false,
		meta: false,
	},
]);
